k: 2


front:

    # data_path: '/data/flower_photos'
    partname: 'front'

    weights: ''
    # 是否冻结权重
    freeze_layers: False
    device: 'cuda:0'
    

    inplanes: 16
    image_size: 32

    wide_list: [16, 16, 32, 64]
 

    ### 0，1，2，3，4 ,5, 6层

    infrop_s: 0
    infrop_e: 3

    seg_para:
        ####  encoder 从1层0个到2层最后一个   
        ## 双闭区间 
        enc:      
            # encoder0
            - [1,0]
            - [1,1]
            - [1,2]
            # encoder1
            - [1,3]
            - [1,4]
            - [2,0]
            - [2,1]
            # encoder2
            - [2,2]
            - [2,3]
            - [2,4]
            - [3,0]
      


         

        ####  decoder 从1层1个到3层第一个  
        ## 双闭区间
        dec: 
            # decoder0
            - [1,1]
            - [1,2]
            - [1,3]
            # decoder1
            - [1,4]
            - [2,0]
            - [2,1]
            - [2,2]
            # decoder2
            - [2,3]
            - [2,4]
            - [3,0]
            - [3,1]
        
       


        


back:

    partname: 'back'

    weights: ''
    # 是否冻结权重
    freeze_layers: False
    device: 'cuda:1'

    inplanes: 64


    wide_list: [16, 16, 32, 64]


    ### 13，14，15层
    ## 辅助网络是仅13，14有

    infrop_s: 3
    infrop_e: 4

    seg_para:

        enc: 
            # encoder3
            - [3,1]
            - [3,2]
            - [3,3]
            - [3,4]

          

        ####  decoder 从1层1个到3层第一个  
        ## 双闭区间
        dec: 
   
          



common:
    # dataset
    dataset: 'CIFAR10'
    # OPTIMIZER
    optimizer: 'SGD'
    lr: 0.1
    lr_decay_rate : 0.1
    lrf: 0.01
    momentum: 0.995
    weight_decay: 0.0001
    cos_lr: False
    milestones : [80, 120]  # 在第 80 和 120 个 epoch 时衰减学习率
    scheduler: False
    adjustlr: False

    model_name: k2_resnet32_ppll_k8
    exp_name: k2_resnet32_ppll_k8


    wide_list: [16, 16, 32, 64]

    image_size: 32
    patch_size: 4

    local_module_num: 8
    batch_size: 1024
    class_num: 10
    dropout_rate: 0
    aux_net_widen: 1
    aux_net_feature_dim: 128

    epochs: 400
    inc_input: True
    ixx_1: 5
    ixy_1: 0.5
    ixx_2: 0
    ixy_2: 0
    
    #AUX
    aux_net_config: '2c2f'
    local_loss_mode: 'cross_entropy'


    InfoPro: 'resnet32'
    layers: [5,5,5]