k: 4


front:

    # data_path: '/data/flower_photos'
    partname: 'front'

    weights: ''
    # 是否冻结权重
    freeze_layers: False
    device: 'cuda:0'
    

    inplanes: 16
    image_size: 32

    wide_list: [16, 16, 32, 64]
 

    ### 0，1，2，3，4 ,5, 6层

    infrop_s: 0
    infrop_e: 8

    seg_para:
        ####  encoder 从1层0个到2层最后一个   
        ## 双闭区间 
        enc:      
            - [1,0]
            - [1,1]
            - [1,2]
            - [1,3]
            - [1,4]
            - [2,0]
            - [2,1]
            - [2,2]

         

        ####  decoder 从1层1个到3层第一个  
        ## 双闭区间
        dec: 
            - [1,1]
            - [1,2]
            - [1,3]
            - [1,4]
            - [2,0]
            - [2,1]
            - [2,2]
            - [2,3]

        




mid: 
    part1:

        partname: 'mid_part1'

        weights: ''

        device: 'cuda:1'
        

        ### 6，7，8, 9层
        inplanes: 32

        infrop_s: 8
        infrop_e: 11

        seg_para:

            enc: 
                - [2,3]
                - [2,4]
                - [3,0]
          

            ####  decoder 从1层1个到3层第一个  
            ## 双闭区间
            dec: 
                - [2,4]
                - [3,0]
                - [3,1]



    part2:

        partname: 'mid_part1'

        weights: ''

        device: 'cuda:2'
        

        ### 10，11，12 层
        inplanes: 64

        infrop_s: 11
        infrop_e: 13

        seg_para:

            enc:      
                - [3,1]
                - [3,2]

          

            ####  decoder 从1层1个到3层第一个  
            ## 双闭区间
            dec: 
                - [3,2]
                - [3,3]





back:

    partname: 'back'

    weights: ''
    # 是否冻结权重
    freeze_layers: False
    device: 'cuda:3'

    inplanes: 64


    wide_list: [16, 16, 32, 64]


    ### 13，14，15层
    ## 辅助网络是仅13，14有

    infrop_s: 13
    infrop_e: 15

    seg_para:

        enc:      
            - [3,3]
            - [3,4]

          

        ####  decoder 从1层1个到3层第一个  
        ## 双闭区间
        dec: 
            - [3,4]



common:
    # dataset
    dataset: 'CIFAR10'
    # OPTIMIZER
    optimizer: 'SGD'
    lr: 0.8
    lr_decay_rate : 0.1
    lrf: 0.01
    momentum: 0.995
    weight_decay: 0.0001
    cos_lr: True
    milestones : [80, 120]  # 在第 80 和 120 个 epoch 时衰减学习率
    scheduler: False
    adjustlr: False

    model_name: k2_resnet32_t
    exp_name: k2_resnet32_t


    wide_list: [16, 16, 32, 64]

    image_size: 32
    patch_size: 4

    local_module_num: 16
    batch_size: 1024
    class_num: 10
    dropout_rate: 0
    aux_net_widen: 1
    aux_net_feature_dim: 128

    epochs: 400
    inc_input: True
    ixx_1: 5
    ixy_1: 0.5
    ixx_2: 0
    ixy_2: 0
    
    #AUX
    aux_net_config: '2c2f'
    local_loss_mode: 'cross_entropy'


    InfoPro: 'resnet32'
    layers: [5,5,5]